### ISSUE TITLE
Do I need to import xev ?

### ISSUE THREAD

**Issue by Pismice** [rsepassi/zigcoro#19]
Hello I am a beginner trying to use your library, I imported "zigcoro" but is that normal that I have to import "libxev" aswell ? Shouldnt it be imported when I import "zigcoro" ?

Also:
- Is there a discord or somewhere I can ask basics questions about how to use the library, I am having a very hard time
- Is this project still alive ?

Thank you and have a nice day :smile:

**Comment by rsepassi** [comment]
Hi, the project is stable and I keep it working as Zig and xev are updated, but I don't expect further changes.

To get a sense for how to use the library with xev, take a look at https://github.com/rsepassi/zigcoro/blob/main/src/test_aio.zig

It imports zigcoro and xev just as you would in your own code.

**Comment by Pismice** [comment]
Yes I realized how to do it, its just that your build.zig.zon only imports libxev but its beceause you have the zigcoro code around you (which i dont in my project).

And is there a discord ? Where should I ask for help if I am having problems using the library ?

**Comment by rsepassi** [comment]
Ok, glad it’s working. There isn’t. You can ask questions on GitHub or
maybe some folks could help out in the main Zig discord.
